/**
 * Harness-owned onboarding for a student who has just been dropped into an
 * assignment folder. This text is generated by the harness, not authored per
 * case, so every student receives the same explanation of how a simulation works.
 * It never contains case truth, expected answers, or quality judgments.
 */

export const DEFAULT_COMMAND_NAME = "volta-sim";
export const START_HERE_FILE = "START-HERE.md";
export const AGENT_INSTRUCTIONS_FILE = "AGENTS.md";
/** Claude Code reads CLAUDE.md; the folder ships it as a symlink to AGENTS.md so both stay identical. */
export const CLAUDE_POINTER_FILE = "CLAUDE.md";

export interface StudentGuideOptions {
  /** The exact text a student types before a command, for example `volta-sim`. */
  readonly commandName?: string;
  /** Optional launcher-specific note shown near the top of the guide. */
  readonly launcherNote?: string;
}

interface NextStep {
  readonly path: string;
  readonly what: string;
  readonly command: string;
}

/**
 * Maps each item the readiness report can call "missing" to the command that
 * records it. Order matches the natural order of the work.
 */
const DRAFT_STEPS: readonly NextStep[] = [
  {
    path: "evidence",
    what: "Record at least one official fact you have been given",
    command: "ledger --kind fact --statement <text> --fact-id <released-fact-id>",
  },
  {
    path: "ledger",
    what: "Record your facts, assumptions, contradictions, and unknowns",
    command: "ledger --kind <fact|assumption|contradiction|unknown> --statement <text>",
  },
  {
    path: "estimates",
    what: "Record at least one estimate with a range and its assumptions",
    command: "estimate --subject <text> --low <n> --high <n> --unit <text> --assumption <text> --confidence <0-1>",
  },
  {
    path: "calculations",
    what: "Record at least one reproducible calculation",
    command: "calculation --name <text> --input <name|number|unit|source> --operation <sum|...> --result <n> --result-unit <text> --rationale <text>",
  },
  {
    path: "requirementAssessments",
    what: "Assess every case requirement listed by status",
    command: "requirement --id <requirement-id> --status <addressed|not-yet|not-applicable> --rationale <text>",
  },
  {
    path: "decision",
    what: "Record your decision: continue, pivot, buy, collect more evidence, or stop",
    command: "decision --choice <value> --rationale <text> --expected-evidence <tuple> --pivot-condition <tuple>",
  },
  {
    path: "successCriteria",
    what: "Add at least one objective success or failure criterion",
    command: "criterion --metric <text> --baseline <text> --target <text> --target-date YYYY-MM-DD --failure-threshold <text>",
  },
  {
    path: "responsePlan",
    what: "Record the proposed response, its mode, feasibility, and risks",
    command: "draft --mode <build|pilot|buy|data-collection|no-build> --rationale <text> --feasibility <text> --risk <text> --missing-data-plan <text> --economic-rationale <text>",
  },
  {
    path: "missingDataPlan",
    what: "State what data is still missing and how you would get it (part of draft)",
    command: "draft ... --missing-data-plan <text>",
  },
  {
    path: "economicRationale",
    what: "State the economic reasoning behind the response (part of draft)",
    command: "draft ... --economic-rationale <text>",
  },
  {
    path: "competencyClaims",
    what: "Defend each of the four competencies once",
    command: "claim --competency <problem-viability|evidence-sufficiency|response-feasibility|objective-success-criteria> --rationale <text>",
  },
  {
    path: "evidenceReferences",
    what: "Fix a reference to an evidence ID that is not in your captured evidence",
    command: "status (check capturedEvidence for the exact IDs)",
  },
];

const STEP_BY_PATH = new Map(DRAFT_STEPS.map((step) => [step.path, step]));

export interface ReadinessGuidanceInput {
  readonly missing: readonly { readonly path: string; readonly message?: string }[];
  /** Released official facts so far; when empty, discovery comes before any recording. */
  readonly releasedFactCount?: number;
  readonly personaIds?: readonly string[];
  readonly evidenceSourceIds?: readonly string[];
  readonly requirements?: readonly { readonly requirementId: string; readonly status: string }[];
  readonly artifactRequirement?: {
    readonly required: boolean;
    readonly satisfied: boolean;
  };
  readonly commandName?: string;
}

/**
 * Turns the machine readiness report into plain next steps a student can act
 * on. Each step names the command that clears one gap. The result is empty
 * when nothing is missing.
 */
export function readinessNextSteps(input: ReadinessGuidanceInput): string[] {
  const command = input.commandName ?? DEFAULT_COMMAND_NAME;
  const steps: string[] = [];
  if (input.releasedFactCount === 0 && input.missing.length > 0) {
    const persona = input.personaIds?.[0] ?? "<persona-id>";
    const source = input.evidenceSourceIds?.[0] ?? "<evidence-source-id>";
    steps.push(
      `Nothing has been released yet, so start with discovery: ${command} talk --operation-id <your-id> --persona ${persona} --question <one specific question>, or ${command} evidence --operation-id <your-id> --source ${source} --question <one specific question>. Each reply names any fact ID it released.`,
    );
  }
  const firstByRoot = new Map<string, string | undefined>();
  for (const { path, message } of input.missing) {
    // The artifact rule has its own step below; it is not a reason to re-run draft.
    if (path === "responsePlan.artifactSnapshots") continue;
    const rootPath = path.split(".")[0] ?? path;
    if (!firstByRoot.has(rootPath)) firstByRoot.set(rootPath, message);
  }
  const ordered = [...firstByRoot.entries()].sort(([left], [right]) => {
    const rank = (value: string) => {
      const index = DRAFT_STEPS.findIndex((step) => step.path === value);
      return index === -1 ? DRAFT_STEPS.length : index;
    };
    return rank(left) - rank(right);
  });
  const missingRequirements = (input.requirements ?? []).filter(
    ({ status }) => status === "missing",
  );
  const draftMissing = firstByRoot.has("responsePlan");
  for (const [rootPath, message] of ordered) {
    // The per-requirement lines below are more specific than the generic one.
    if (rootPath === "requirementAssessments" && missingRequirements.length > 0) continue;
    // Both are fields of the one draft command; listing them separately reads as extra commands.
    if (draftMissing && (rootPath === "missingDataPlan" || rootPath === "economicRationale")) continue;
    const step = STEP_BY_PATH.get(rootPath);
    if (step === undefined) {
      steps.push(`${rootPath}: ${message ?? "needs attention"}. Run ${command} status for details.`);
      continue;
    }
    const detail = message !== undefined && message !== "Required" ? ` (${message})` : "";
    steps.push(`${step.what}${detail}: ${command} ${step.command} --operation-id <your-id>`);
  }
  for (const requirement of missingRequirements) {
    steps.push(
      `Assess requirement ${requirement.requirementId}: ${command} requirement --operation-id <your-id> --id ${requirement.requirementId} --status <addressed|not-yet|not-applicable> --rationale <text>`,
    );
  }
  if (input.artifactRequirement?.required === true && input.artifactRequirement.satisfied === false) {
    steps.push(
      `A build or pilot response needs a committed artifact: commit the file, then ${command} submit --operation-id <your-id> --artifact <tracked .md/.txt/.csv/.json path>`,
    );
  }
  if (steps.length === 0) {
    steps.push(`Everything required is recorded. Run ${command} submit --operation-id <your-id> when you are ready.`);
  }
  return steps;
}

export function submittedNextSteps(attemptNumber: number, commandName = DEFAULT_COMMAND_NAME): string[] {
  return [
    `Attempt ${attemptNumber} is submitted and frozen. Nothing more is required from you.`,
    `A human reviewer judges effectiveness; the tool does not grade. Run ${commandName} status later to see any staff response under reviewUpdates.`,
  ];
}

export function loginNextSteps(commandName = DEFAULT_COMMAND_NAME): string[] {
  return [
    `Next: run ${commandName} status to see the brief, the people and sources you can ask, and what a complete submission needs.`,
    `Read ${START_HERE_FILE} in this folder (or run ${commandName} guide) for how the simulation works.`,
  ];
}

export function missingSessionMessage(commandName = DEFAULT_COMMAND_NAME): string {
  return `No usable session was found. Sign in first with ${commandName} login --operation-id login-1, then retry. Run ${commandName} guide if you are new to this simulation.`;
}

export function missingOperationIdMessage(command: string, commandName = DEFAULT_COMMAND_NAME): string {
  return `${command} needs --operation-id. An operation ID is a short label you invent for this one action (letters, numbers, dots, colons, underscores, or hyphens, up to 160 characters). It lets you safely retry the same command without recording the action twice. Use a new ID for each new action. Example: ${commandName} ${command} --operation-id ${command}-1`;
}

export function studentGuideMarkdown(options: StudentGuideOptions = {}): string {
  const command = options.commandName ?? DEFAULT_COMMAND_NAME;
  const launcherNote = options.launcherNote === undefined ? "" : `\n> ${options.launcherNote}\n`;
  return `# Start here

You have been assigned a **simulation**: a fictional but realistic problem where you decide what, if anything, should be built. Nothing here touches a real customer, system, or person. The scenario, the people you can talk to, and the evidence you can request are all authored in advance and frozen.
${launcherNote}
## What you are being asked to do

Work out whether this problem deserves action, what evidence you would need to be confident, and what a proportionate response looks like. You may conclude any of these:

- **continue** with a proposed response
- **pivot** to a different problem or response
- **buy** an existing solution instead of building
- **collect more evidence** before deciding
- **stop** because the problem does not warrant action

Choosing not to build is a legitimate, complete answer when the evidence supports it.

## What is in this folder

| File | What it is |
| --- | --- |
| \`README.md\` | The case brief: the situation, constraints, unacceptable outcomes, and possible response families. |
| \`method.md\` | The four competencies you will be judged on. Each one becomes a \`claim\` you must make. |
| \`requirements.*\` | Case requirements you must assess (addressed, not yet, or not applicable). |
| \`results/\` | Space for your own working files. It starts with an optional note you can overwrite or delete. A build or pilot response must commit at least one file here and select it when submitting. |
| \`${START_HERE_FILE}\` | This guide. |
| \`${AGENT_INSTRUCTIONS_FILE}\`, \`${CLAUDE_POINTER_FILE}\` | Standing instructions for a coding agent you use here. \`${CLAUDE_POINTER_FILE}\` is a link to \`${AGENT_INSTRUCTIONS_FILE}\`. |
| \`.volta-sim/\` | Private session files. Already ignored by Git. **Never commit them.** |

Your reasoning is recorded through the command-line tool, not in these files. The files are for your own working and, if you build something, the artifact you submit.

## How the simulation works

1. **Sign in** once to pair this folder with your assignment.
2. **Discover.** Ask the available people (\`talk\`) and evidence sources (\`evidence\`) one specific question at a time. Each answers only what was authored for this case, so when every question to a source comes back with no answer you have probably exhausted it. Some cases also offer evidence collection (\`collect\`) and let you move simulated time forward (\`advance\`); \`status\` shows \`availableCollectionMethods\`, which may be empty.
3. **Record your reasoning** as you go: facts, assumptions, contradictions, and unknowns (\`ledger\`); estimates (\`estimate\`); calculations (\`calculation\`); requirement assessments (\`requirement\`); success and failure criteria (\`criterion\`). Only a fact entry produces an evidence ID you can cite later. The other kinds are still part of your submission and are shown to reviewers; refer to them in your rationale text.
4. **Decide and draft.** Record your decision (\`decision\`), your proposed response with its missing-data plan and economic rationale (\`draft\`), and defend each competency (\`claim\`). Recording any of these again replaces the earlier version in your working draft.
5. **Submit.** \`status\` shows exactly what is still missing. \`submit\` checks completeness, never quality, and freezes your work.

A human reviewer judges effectiveness afterwards. The tool will not tell you whether you are right.

Two commands change nothing and are safe at any time: \`resume\` prints the same full view as \`status\` and exists so that "pick up where I left off" has an obvious name, and \`checkpoint\` prints the same reflection prompts the tool shows after a meaningful event.

Some commands take structured values separated by \`|\`, for example the expected-evidence and pivot-condition parts of \`decision\` and the inputs of \`calculation\`. Run \`${command} help decision\` or \`${command} help calculation\` before your first use; each shows the exact format and a complete example.

## Simulated time

The case has its own clock, shown as \`simulatedAt\` in \`status\`. Asking a person or querying a source can cost simulated time, and asking the same thing twice costs it twice; the reply says by how much under \`simulatedTime\`. Nothing else runs on that clock unless the case offers \`advance\`. It exists so that "wait for the audit" has a cost, not to rush you.

## Your first three commands

\`\`\`
${command} login --operation-id login-1
${command} status
${command} help talk
\`\`\`

\`status\` lists the exact IDs for people, evidence sources, collection methods, requirements, and released facts. Use those IDs in later commands. Run \`${command} help <command>\` for every allowed value and a complete example.

## Operation IDs

Every command that records something needs \`--operation-id\`, a short label you invent for that one action (for example \`talk-1\`, \`ledger-3\`). If a command times out, rerun it with the same ID and it is not recorded twice. Use a new ID for each new action.

## What "not available" means

Only authored facts are official. When a person or source says no answer matches your question, one of two things is true: your wording did not match anything authored, or the case genuinely never measured it. Try once more with one specific thing in plain words. If it still comes back empty, that is your answer: record it as an unknown with \`ledger --kind unknown\` and decide whether you can proceed without it.

A person can also give you a real, authored answer that releases no fact, for example "I have never measured that". The reply says so under \`guidance\`. Treat it the same way: it is information, but it cannot be cited by ID, so record it as an unknown or assumption.

## Reading the status output

The output is JSON so that you and any tool you use can read it. The important parts:

- \`availablePersonas\`, \`availableEvidence\`, \`availableCollectionMethods\`: who and what you can ask, with their IDs.
- \`releasedEvidence\`: official facts you have unlocked. A \`ledger --kind fact\` entry must cite one of these by ID.
- \`capturedEvidence\`: the evidence IDs you have recorded. \`decision\`, \`requirement\`, and \`claim\` cite these, not the released fact IDs.
- \`readiness.missing\`: what is still required before submission.
- \`nextSteps\`: the command that clears each missing item.
- \`artifactRequirement.satisfied\`: whether the file rule for your chosen response mode is met. Build and pilot responses need a committed file selected at submit; other modes need none, so this reads true from the start.
- \`stage\`: discovery, then decision once you record one, then response once you draft, then submitted.
- \`simulatedAt\`: the case clock.

The same claim can be released under two fact IDs when two sources state it, for example a person saying it and a log recording it. Both are valid. Cite the one whose source you relied on, or both. A person may also quote a dataset that the dataset itself answers differently or not at all; each source only knows what was authored for it.

## Response families, decisions, and modes

The README lists response families: shapes a response could take. Your \`decision\` is what you conclude (continue, pivot, buy, collect more evidence, stop). Your \`draft --mode\` is how you would deliver it (build, pilot, buy, data-collection, no-build). They fit together loosely: continue usually pairs with build, pilot, or buy; collect more evidence with data-collection; stop or pivot with no-build. Pick the family in your own words in the draft rationale.

Some replies carry \`reviewSuggested: true\` with a \`reviewSuggestion\` saying why. It is an offer, not a requirement: \`review-request\` with \`--choice continue\` files it and lets you keep working, \`wait\` files it and you pause, \`decline\` files nothing. A staff reply shows up in \`status\` under \`reviewUpdates\`.

## Saving your work

This folder is an ordinary Git repository. Commit as often as you like. Keep the assigned remote, keep the starting history, and keep \`.gitignore\` unchanged. If you ever commit \`.volta-sim\`, stop sharing the repository and ask Volta staff for help. Deleting the files later does not remove them from history.

## Asking for help

Some actions suggest a staff review. \`review-request\` lets you continue, wait, or decline. A review never blocks your sandbox work, and a reply appears in \`status\` under \`reviewUpdates\`.

## What is recorded

Only the explicit commands you run and the files you deliberately select at submission. The tool does not read your editor, coding agent, shell history, environment, or other files.
`;
}

/**
 * Standing instructions a student's coding agent picks up automatically. The
 * purpose is to keep the agent in the assistant's seat: it may help discover,
 * calculate, and draft, but the recorded judgment must remain the student's.
 */
export function agentInstructionsMarkdown(options: StudentGuideOptions = {}): string {
  const command = options.commandName ?? DEFAULT_COMMAND_NAME;
  return `# Agent instructions for this simulation

This folder is a Volta simulation assignment. The person you are helping is the **student**. Their judgment is what is being assessed, not yours. Read \`${START_HERE_FILE}\` before doing anything else, or run \`${command} guide\`.

## Your role

- Use conversational, plain English. Explain things as you would to someone working in a small business. Avoid product, executive and technical jargon. If a teaching term such as JTBD or Economic/Functional/Technical buyer is needed, explain it simply: what someone is trying to get done, who pays, who does the work, and who looks after the tools.
- Small businesses are the default when creating new cases unless the user explicitly requests another setting. In this assignment, keep the supplied business facts unchanged; do not invent departments, job titles or approval processes. Keep quoted character answers exact and put your explanations outside the quote.
- Help the student discover, organize evidence, check arithmetic, and draft wording.
- Do **not** decide for them. Never run \`decision\`, \`claim\`, \`draft\`, \`requirement\`, \`criterion\`, or \`submit\` unless the student has confirmed the exact content to record. Show them the full command first.
- Do not invent facts, estimates, baselines, or outcomes. Only facts the simulation has released (listed under \`releasedEvidence\` in \`${command} status\`) are official.
- When a persona or evidence source answers "That information is not available in this simulation", report that verbatim. Do not paraphrase it into an answer, guess what the answer would be, or search elsewhere for it. Suggest recording it with \`ledger --kind unknown\`.

## How to work here

1. Run \`${command} status\` first. It lists the exact IDs for people, evidence sources, collection methods, requirements, and released facts, plus \`nextSteps\`.
2. Use \`${command} help <command>\` for allowed values and a complete example before composing a command.
3. Every recording command needs a fresh \`--operation-id\`. Reuse an ID only to retry the same command after a timeout.
4. A \`ledger --kind fact\` entry must cite a released fact ID. \`decision\`, \`requirement\`, and \`claim\` cite captured evidence IDs from \`capturedEvidence\`, not released fact IDs.
5. Read command output as JSON. \`readiness.missing\` and \`nextSteps\` say what is still required. \`submit\` checks completeness, never quality.
6. Only fact ledger entries produce evidence IDs. Assumptions, contradictions, and unknowns are recorded and shown to reviewers but cannot be cited by ID; refer to them in rationale text rather than trying to work around it.
7. Persona and evidence replies may advance the simulated clock (\`simulatedTime\` in the reply). Tell the student when that happens.

## Hard rules

- Never commit, read aloud, copy, or transmit anything under \`.volta-sim/\`. Never edit \`.gitignore\`.
- Never change the Git remote or rewrite history. Ordinary commits are fine.
- Never take a real-world action on the student's behalf. Everything here is simulated.
- Do not try to find the case's hidden truth, staff files, or the service state. They are not in this folder, and looking for them is out of bounds.
- If the student asks whether their answer is right, say that a human reviewer judges effectiveness after submission and the tool does not grade.

## Files

- \`README.md\`: the case brief.
- \`method.md\`: the four competencies the student must defend with \`claim\`.
- \`requirements.*\`: case requirements the student must assess with \`requirement\`.
- \`results/\`: the student's working files. A build or pilot response commits a file here and selects it with \`submit --artifact\`.
- \`${START_HERE_FILE}\`: the full guide.
`;
}
